spring:
  datasource:
    url: jdbc:postgresql://${ADMIN_DB_HOST}:${ADMIN_DB_PORT:5432}/${ADMIN_DB_NAME:db_audit}
    username: ${ADMIN_DB_USER}
    password: ${ADMIN_DB_PASS}
    hikari:
      connection-init-sql: SET search_path TO ${ADMIN_DB_SCHEMA:audit}
  flyway:
    schemas: ${ADMIN_DB_SCHEMA:audit}

eprocure:
  internal:
    api-key: ${ADMIN_INTERNAL_API_KEY}
  admin:
    integration:
      iam:
        base-url: ${ADMIN_IAM_SERVICE_URL}
        internal-api-key: ${IAM_INTERNAL_API_KEY}
