-- V1__create_audit_log_foundation.sql
-- Migration: Create immutable audit log table for Admin Portal read APIs
-- Date: 2026-06-15

CREATE SCHEMA IF NOT EXISTS audit;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS audit.audit_logs (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    actor_id        UUID            NOT NULL,
    actor_name      VARCHAR(200)    NOT NULL,
    actor_roles     VARCHAR(50)[],
    actor_ip        INET,
    session_id      VARCHAR(100),
    action          VARCHAR(100)    NOT NULL,
    entity_type     VARCHAR(50)     NOT NULL,
    entity_id       UUID,
    entity_number   VARCHAR(50),
    occurred_at     TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    http_method     VARCHAR(10),
    endpoint        VARCHAR(500),
    request_id      VARCHAR(100),
    is_success      BOOLEAN         NOT NULL,
    error_code      VARCHAR(50),
    old_value       JSONB,
    new_value       JSONB,
    description     TEXT,
    service_name    VARCHAR(50)     NOT NULL,
    CONSTRAINT pk_audit_logs PRIMARY KEY (id, occurred_at),
    CONSTRAINT chk_audit_logs_http_method CHECK (
        http_method IS NULL OR http_method IN ('GET', 'POST', 'PUT', 'PATCH', 'OPTIONS')
    )
) PARTITION BY RANGE (occurred_at);

CREATE TABLE IF NOT EXISTS audit.audit_logs_2025 PARTITION OF audit.audit_logs
    FOR VALUES FROM ('2025-01-01') TO ('2026-01-01');

CREATE TABLE IF NOT EXISTS audit.audit_logs_2026 PARTITION OF audit.audit_logs
    FOR VALUES FROM ('2026-01-01') TO ('2027-01-01');

CREATE TABLE IF NOT EXISTS audit.audit_logs_default PARTITION OF audit.audit_logs DEFAULT;

COMMENT ON TABLE audit.audit_logs IS 'Immutable audit trail for security, admin, and business operations.';
COMMENT ON COLUMN audit.audit_logs.actor_id IS 'User ID of actor that performed the audited action.';
COMMENT ON COLUMN audit.audit_logs.actor_roles IS 'Role codes captured at action time.';
COMMENT ON COLUMN audit.audit_logs.action IS 'Business action code such as PR.SUBMITTED or CONFIG.UPDATED.';
COMMENT ON COLUMN audit.audit_logs.old_value IS 'JSON snapshot before the change; append-only audit data.';
COMMENT ON COLUMN audit.audit_logs.new_value IS 'JSON snapshot after the change; append-only audit data.';

CREATE INDEX IF NOT EXISTS idx_audit_actor ON audit.audit_logs(actor_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit.audit_logs(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_action ON audit.audit_logs(action, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_service ON audit.audit_logs(service_name, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_success ON audit.audit_logs(is_success, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_occurred ON audit.audit_logs(occurred_at DESC);
