import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { provideRouter } from '@angular/router';
import {
  LucideActivity,
  LucideAlertTriangle,
  LucideArrowLeft,
  LucideBadgeCheck,
  LucideBan,
  LucideBell,
  LucideBox,
  LucideBuilding2,
  LucideCalendarDays,
  LucideChartNoAxesCombined,
  LucideCheck,
  LucideCheckCircle,
  LucideCheckCircle2,
  LucideChevronLeft,
  LucideChevronRight,
  LucideChevronDown,
  LucideChevronUp,
  LucideCircle,
  LucideCircleAlert,
  LucideCircleOff,
  LucideClock,
  LucideClipboardList,
  LucideCopy,
  LucideDownload,
  LucideExternalLink,
  LucideEye,
  LucideEyeOff,
  LucideFileCode2,
  LucideFilePenLine,
  LucideFilePlus2,
  LucideFileSearch,
  LucideFileText,
  LucideFilter,
  LucideFilterX,
  LucideFolder,
  LucideGitBranch,
  LucideGlobe,
  LucideHistory,
  LucideHome,
  LucideInbox,
  LucideInfo,
  LucideKey,
  LucideKeyRound,
  LucideLanguages,
  LucideLayers,
  LucideLayoutDashboard,
  LucideList,
  LucideListChecks,
  LucideListFilter,
  LucideLoaderCircle,
  LucideLock,
  LucideLogIn,
  LucideLogOut,
  LucideMail,
  LucideMapPinOff,
  LucideMenu,
  LucideNetwork,
  LucidePackage,
  LucidePackageCheck,
  LucidePackageSearch,
  LucidePackageX,
  LucidePaperclip,
  LucidePencil,
  LucidePin,
  LucidePlus,
  LucideReceiptText,
  LucideRefreshCw,
  LucideRotateCcw,
  LucideRows3,
  LucideSave,
  LucideSearch,
  LucideSend,
  LucideSettings,
  LucideShield,
  LucideShieldAlert,
  LucideShieldCheck,
  LucideShieldOff,
  LucideShoppingCart,
  LucideSlidersHorizontal,
  LucideStar,
  LucideTruck,
  LucideUploadCloud,
  LucideUser,
  LucideUserCog,
  LucideUsers,
  LucideWarehouse,
  LucideWorkflow,
  LucideTrash2,
  LucideX,
  LucideXCircle,
  LucideFilePlus,
  LucideScale,
  LucideAward,
  LucideFileCheck2,
  LucideScanSearch,
  LucideBanknote,
  LucideCalculator,
  LucideCalendarClock,
  LucideFileDown,
  LucideGauge,
  LucideBarChart3,
  LucideWalletCards,
  LucideFactory,
  LucideWallet,
  LucideAlarmClock,
  LucideTimer,
  LucideLineChart,
  LucideBoxes,
  LucideArchiveX,
  LucideTags,
  LucideBarcode,
  LucidePackageMinus,
  LucideRepeat2,
  LucidePackagePlus,
  LucideClock3,
  LucideCoins,
  provideLucideConfig,
  provideLucideIcons
} from '@lucide/angular';
import { provideTranslateService } from '@ngx-translate/core';
import { provideTranslateHttpLoader } from '@ngx-translate/http-loader';

import { routes } from './app.routes';
import { environment } from '../environments/environment';
import { API_BASE_URL, ENCRYPTION_ENABLED, WS_BASE_URL } from './core/http/api-tokens';
import { credentialsInterceptor } from './core/http/credentials.interceptor';
import { encryptionInterceptor } from './core/http/encryption.interceptor';
import { errorInterceptor } from './core/http/error.interceptor';
import { idempotencyInterceptor } from './core/http/idempotency.interceptor';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes),
    provideHttpClient(
      withInterceptors([
        credentialsInterceptor,
        idempotencyInterceptor,
        encryptionInterceptor,
        errorInterceptor
      ])
    ),
    provideTranslateService({
      fallbackLang: 'vi',
      lang: 'vi',
      loader: provideTranslateHttpLoader({
        prefix: '/assets/i18n/',
        suffix: '.json'
      })
    }),
    provideLucideIcons(
      LucideActivity,
      LucideAlertTriangle,
      LucideArrowLeft,
      LucideBadgeCheck,
      LucideBan,
      LucideBell,
      LucideBox,
      LucideBuilding2,
      LucideCalendarDays,
      LucideChartNoAxesCombined,
      LucideCheck,
      LucideCheckCircle,
      LucideCheckCircle2,
      LucideChevronLeft,
      LucideChevronRight,
      LucideChevronDown,
      LucideChevronUp,
      LucideCircle,
      LucideCircleAlert,
      LucideCircleOff,
      LucideClock,
      LucideClipboardList,
      LucideCopy,
      LucideDownload,
      LucideExternalLink,
      LucideEye,
      LucideEyeOff,
      LucideFileCode2,
      LucideFilePenLine,
      LucideFilePlus2,
      LucideFileSearch,
      LucideFileText,
      LucideFilter,
      LucideFilterX,
      LucideFolder,
      LucideGitBranch,
      LucideGlobe,
      LucideHistory,
      LucideHome,
      LucideInbox,
      LucideInfo,
      LucideKey,
      LucideKeyRound,
      LucideLanguages,
      LucideLayers,
      LucideLayoutDashboard,
      LucideList,
      LucideListChecks,
      LucideListFilter,
      LucideLoaderCircle,
      LucideLock,
      LucideLogIn,
      LucideLogOut,
      LucideMail,
      LucideMapPinOff,
      LucideMenu,
      LucideNetwork,
      LucidePackage,
      LucidePackageCheck,
      LucidePackageSearch,
      LucidePackageX,
      LucidePaperclip,
      LucidePencil,
      LucidePin,
      LucidePlus,
      LucideReceiptText,
      LucideRefreshCw,
      LucideRotateCcw,
      LucideRows3,
      LucideSave,
      LucideSearch,
      LucideSend,
      LucideSettings,
      LucideShield,
      LucideShieldAlert,
      LucideShieldCheck,
      LucideShieldOff,
      LucideShoppingCart,
      LucideSlidersHorizontal,
      LucideStar,
      LucideTruck,
      LucideUploadCloud,
      LucideUser,
      LucideUserCog,
      LucideUsers,
      LucideWarehouse,
      LucideWorkflow,
      LucideTrash2,
      LucideX,
      LucideXCircle,
      LucideFilePlus,
      LucideScale,
      LucideAward,
      LucideFileCheck2,
      LucideScanSearch,
      LucideBanknote,
      LucideCalculator,
      LucideCalendarClock,
      LucideFileDown,
      LucideGauge,
      LucideBarChart3,
      LucideWalletCards,
      LucideFactory,
      LucideWallet,
      LucideAlarmClock,
      LucideTimer,
      LucideLineChart,
      LucideBoxes,
      LucideArchiveX,
      LucideTags,
      LucideBarcode,
      LucidePackageMinus,
      LucideRepeat2,
      LucidePackagePlus,
      LucideClock3,
      LucideCoins
    ),
    provideLucideConfig({
      strokeWidth: 1.8,
      absoluteStrokeWidth: true
    }),
    { provide: API_BASE_URL, useValue: environment.apiBaseUrl },
    { provide: WS_BASE_URL, useValue: environment.wsBaseUrl },
    { provide: ENCRYPTION_ENABLED, useValue: environment.encryptionEnabled }
  ]
};
